### ISSUE TITLE
old arm-angle definition

### ISSUE THREAD

**Issue by theotromp97** [BerkeleyAutomation/gqcnn#102]
Dear,

I have successfully installed yumipy and can make a connection with the yumi successfully.
My problem is regarding a newer version of RobotStudio (6.0.8).
My problem is basically the same as [THIS](https://forums.robotstudio.com/discussion/10324/how-to-set-yumis-configuration-when-using-move-instruction) thread.
When i try a goto_pose() command I get the same error as in the link above.
In RobotStudio V6.0.8 there is no option anymore to use old arm angle definition so this solution does not work in this version.
Using a previous version of RobotStudio is not really an option so I need a solution to change the arm-angle definition. 

Thanks in advance.
Best regards,
Theo

**Comment by visatish** [comment]
Hi @theotromp97,

Can you raise this issue in the [yumipy](https://github.com/BerkeleyAutomation/yumipy) repo instead?

Thanks,
Vishal
