### ISSUE TITLE
Issue: Bug with analyze_gqcnn_performance

### ISSUE THREAD

**Issue by anmakon** [BerkeleyAutomation/gqcnn#111]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04)
- Python version: 3.5.2
- Installed using pip or ROS: pip

**Describe what you are trying to do**

I'm trying to analyse a gqcnn network (trained on dexnet-2.0) on a custom dataset.

**Describe current behaviour**

When running `python tools/analyze_gqcnn_performance GQCNN-2.0 --dataset_config_filename my/config/file`, it can't find "log_rate" in the config file.

**Fix for the current behaviour** 

In tools/analyze_gqcnn_performance, line 103 the variable config_filename is overwritten by what should be dataset_config_filename if the --datset_config_filename flag is set. Changing `config_filename` to `dataset_config_filename` solves the issue.

**Comment by visatish** [comment]
Hi @anmakon,

Thanks for pointing this out! I missed it because we normally don't use this flag since we analyze models on the datasets they were trained on. It has been patched in https://github.com/BerkeleyAutomation/gqcnn/pull/113!.

Thanks,
Vishal
