### ISSUE TITLE
How to generate the synthetic training dataset ?

### ISSUE THREAD

**Issue by gachiemchiep** [BerkeleyAutomation/gqcnn#125]
Hello. 
Thank you for publishing your amazing work. 

I have two questions :
1. Are the scripts used for generating the training dataset available?
2. Is there a quick summary of the format of the training dataset. I understood the depth data, but I couldn't understand about the grasping point and how they are defined.

**Comment by qingweihk** [comment]
> Hello. Thank you for publishing your amazing work.
> 
> I have two questions :
> 
> 1. Are the scripts used for generating the training dataset available?
> 2. Is there a quick summary of the format of the training dataset. I understood the depth data, but I couldn't understand about the grasping point and how they are defined.

Hi, My I ask where can we find  the scripts used for generating the training dataset?
Thansks a lot!
