### ISSUE TITLE
Compatibility with Perception / no module named CameraInstrinsics

### ISSUE THREAD

**Issue by Greg8978** [BerkeleyAutomation/gqcnn#127]
For anyone who may have the same issue, this repo isn't compatible with the last version of perception.

CameraInstrinsics has been removed in [this commit](https://github.com/BerkeleyAutomation/perception/commit/1dd48f392bc3777b2111636180cdac31d620751d), making it unable to execute gqcnn.

I solved it by reverting the perception repo :)

**Comment by mjd3** [comment]
These modules were ported over to `autolab_core`. The latest commit fixes this issue; sorry about that!
