### ISSUE TITLE
Issue: Installation Issue: [Cannot download pre-trained model and training datasets]

### ISSUE THREAD

**Issue by SonYeongGwang** [BerkeleyAutomation/gqcnn#133]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Python version: 3.5
- Installed using pip or ROS: pip

Hi, thank you for sharing and having us to have opportunity to refer such a great work.
I found that downloading the pre-trained model and datasets are no longer support in (https://berkeley.app.box.com/s/szbchyt3tou9e4ct6dz8c5v99vhx0s84)
I ask you to have alternative way to find the sources!

Thanks

**Comment by timdreier** [comment]
Same problem for me. Would be great if they would be accessible again!

**Comment by timdreier** [comment]
@SonYeongGwang seems like the files are accessible again!

**Comment by SonYeongGwang** [comment]
It seems like! Thank you for letting me know!

**Comment by manish-kumar-01** [comment]
@SonYeongGwang Again, the trained models are inaccessible.

**Comment by SonYeongGwang** [comment]
@manish-kumar-01 I guess they moved the like from 'box' to 'g-drive'. You can find the google drive directly linked to the dexnet models at https://berkeleyautomation.github.io/dex-net/
