### ISSUE TITLE
No such file or directory: '/home/autolab/Public/data/dex-net/data/grasp_quality_regression/3dnet_kit_04_09_17_minimal'

### ISSUE THREAD

**Issue by benzben** [BerkeleyAutomation/gqcnn#22]
Hi,
we tried to start the sample visualization of the GQCNN Package as in https://berkeleyautomation.github.io/gqcnn/tutorials/tutorial.html .
Unfortunately we stumble upon the error
No such file or directory: '/home/autolab/Public/data/dex-net/data/grasp_quality_regression/3dnet_kit_04_09_17_minimal'
after starting the last command:

visualizer = GQCNNPredictionVisualizer(visualization_config)

Output:
INFO:root:Setting up for visualization.
INFO:root:Reading filenames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gqcnn/gqcnn_prediction_visualizer.py", line 56, in __init__
    self._setup()
  File "gqcnn/gqcnn_prediction_visualizer.py", line 198, in _setup
    self._setup_data_filenames()
  File "gqcnn/gqcnn_prediction_visualizer.py", line 214, in _setup_data_filenames
    all_filenames = os.listdir(self.data_dir)
OSError: [Errno 2] No such file or directory: '/home/autolab/Public/data/dex-net/data/grasp_quality_regression/3dnet_kit_04_09_17_minimal'
>>> visualizer.visualize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'visualizer' is not defined

Why is there no folder "autolab"? We installed the autolab_core and perception packages.

Thanks in advance :-)

**Comment by visatish** [comment]
Hi benzben! Sorry about that, there is actually an error in the visualizer config file located at cfg/tools/gqcnn_prediction_visualizer.yaml where the dataset_dir and model_dir parameters are actually pointing to paths on our machine for testing...they should actually point to the location of the dataset you trained the GQCNN model on, and the location of the trained model, respectively. I will push a fix to this soon, sorry for the confusion!
