### ISSUE TITLE
The wrong predictions

### ISSUE THREAD

**Issue by pyni** [BerkeleyAutomation/gqcnn#26]
Hi, i use realsense r300, and i send the ROS message to gqcnn.
However, the result is shown as follows:

![screenshot from 2018-06-21 16-20-35](https://user-images.githubusercontent.com/18031767/41706750-2500a48a-756f-11e8-987b-9a0bf2bd67ef.png)
![screenshot from 2018-06-21 16-20-47](https://user-images.githubusercontent.com/18031767/41706751-254890ec-756f-11e8-86ea-0bed9dede1fb.png)
![screenshot from 2018-06-21 16-20-56](https://user-images.githubusercontent.com/18031767/41706753-25946bb6-756f-11e8-9e8c-8a026f294545.png)
![screenshot from 2018-06-21 16-21-10](https://user-images.githubusercontent.com/18031767/41706754-25e211d6-756f-11e8-9694-7cc8f21c55c0.png)

I can hardly understand why the grasps are shown like that?

**Comment by jeffmahler** [comment]
@pyni Thanks for raising this issue. It seems that the depth image you are sending GQ-CNN has large white areas of missing data. This is likely causing the grasp sampler to sample grasps that are too close or too far from the camera: "large" grasps correspond to grasps close to the camera and "small" grasps are far away.

One option is to turn on inpainting in the grasp_planner_node as we do in [our example YuMi code](https://github.com/BerkeleyAutomation/gqcnn/blob/26187e2fb53fff47dbd1cdb19921ed8a9e102396/ros_nodes/yumi_control_node.py#L269). This should probably be the default in the grasp_planner_node... The quick fix is to add those two inpainting lines to [these lines of the grasp_planner_node](https://github.com/BerkeleyAutomation/gqcnn/blob/26187e2fb53fff47dbd1cdb19921ed8a9e102396/ros_nodes/yumi_control_node.py#L269).

@visatish Can you take a look at making inpainting the default behavior in the ROS grasp planning service?

@pyni We can also help debug if you enable logging and re-run this example. To do this, please add a field "logging_dir" pointing to a directory of your choice under the "policy" key in the grasp planner node YAML config file. The default file is [here](https://github.com/BerkeleyAutomation/gqcnn/blob/master/cfg/ros_nodes/grasp_planner_node.yaml) -- not sure if you made your own.

When you re-run, the inputs and outputs to the policy will be saved in the logging_dir. Then you can upload or email me those files and I can take a look.

**Comment by pyni** [comment]
Thanks for replying! I'll try it later.

**Comment by pyni** [comment]
- 
![sss](https://user-images.githubusercontent.com/18031767/42275886-4c8734b0-7fc4-11e8-8e8e-29a89a85d48f.png)
Hi, I have done want you told, but the inpainted result is quite strange.

And the final grasp detection result is still the same with the uninpainting result.

**Comment by pyni** [comment]
I think maybe the problem of the inpainting algorithm.

**Comment by pyni** [comment]
i have found the problem. That is the problem of my depth image.
