### ISSUE TITLE
Normal may be not right

### ISSUE THREAD

**Issue by pyni** [BerkeleyAutomation/gqcnn#32]
Hello, i try the suction code.
But i find the calculation for the normals may be not right.

For example：
![image](https://user-images.githubusercontent.com/18031767/43262711-b77168f8-9113-11e8-9f96-5a0927efd986.png)
and the i do the following in suction_policy.py：

print action.grasp.axis

The output for the normal of the red point is [-0. -0.  1.]

But obviously this is not right.

So i wonder whether the calculation of the normal for your code has some limitation.

**Comment by bderose** [comment]
@pyni: This might be helpful for you https://github.com/BerkeleyAutomation/gqcnn/pull/34 It appears there is a problem with the normal computation.

**Comment by pyni** [comment]
Thanks.
I'll try it later.

**Comment by eric-tc** [comment]
Hi @pyni i'm facing the same issue.
Did you find a way to solve this?

Thanks
