### ISSUE TITLE
Catkin make install problem on ROS Kinetic

### ISSUE THREAD

**Issue by vfdev-5** [BerkeleyAutomation/gqcnn#35]
Hi

Just to inform that there is a small problem of versions between package.xml (0.1.0) and `__version__` in the setup.py (0.0.2) such that `catkin_make` fails to build the package (on ROS Kinetic).
Change of `__version__ = 0.1.0` fixes the problem

HTH

**Comment by vfdev-5** [comment]
I see this is fixed in `merge_jeff`, so close the issue

**Comment by jeffmahler** [comment]
Thank you for raising this issue. We will fix in the master version as soon as possible
