### ISSUE TITLE
kinect2 sensor type

### ISSUE THREAD

**Issue by wjydou** [BerkeleyAutomation/gqcnn#51]
in rgbd_sensors.py , s = KinectSensorBridged(quality=cfg['quality'], frame=cfg['frame'])
In cfg/examples/policy.yaml,the sensor: type: bridged_kinect2
and what is the quality put in the policy.yaml?
 Thank you.

**Comment by SimonePanicucci** [comment]
@wjydou have you succesfully set up the Kinect2 sensor?
I'm trying as well, do you have some suggestion for me?
Many thanks.
