### ISSUE TITLE
Ros Service Launch Error

### ISSUE THREAD

**Issue by jiuweifox** [BerkeleyAutomation/gqcnn#52]
I want to start the serive of gqcnn but failed. The info is like next, 

NODES
  /
    GQCNN_grasp_planner (gqcnn/grasp_planner_node.py)

auto-starting new master
process[master]: started with pid [17722]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 355ddcf4-4949-11e9-9d57-f4d108abcd6d
process[rosout-1]: started with pid [17735]
started core service [/rosout]
Unable to launch [GQCNN_grasp_planner-2]. 
If it is a script, you may be missing a '#!' declaration at the top.
The traceback for the exception was written to the log file
[GQCNN_grasp_planner-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit

Anybody can help me?  Thanks very much

**Comment by jeffmahler** [comment]
Try putting `#!/usr/bin/python` at the top of `grasp_planner_node.py`. I'm not sure why it's necessary on your machine though.

**Comment by jiuweifox** [comment]
> Try putting `#!/usr/bin/python` at the top of `grasp_planner_node.py`. I'm not sure why it's necessary on your machine though.

Thanks very much!  It worked.
