### ISSUE TITLE
Issue: Bug/Performance Issue [Replication]

### ISSUE THREAD

**Issue by zuoym15** [BerkeleyAutomation/gqcnn#99]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Python version: 2.7
- Installed using pip or ROS: pip
- GPU model (if applicable):

**Describe the result you are trying to replicate**
If you can, provide a link to the section in the [documentation]
https://github.com/BerkeleyAutomation/gqcnn/blob/master/scripts/training/train_dex-net_2.0.sh

**Provide the exact sequence of commands / steps that you executed to replicate this result**

**Describe the unexpected behavior** 
I'm trying to replicate the result from the Dex-Net 2.0 paper and I have a few questions. I would be much appreciated if you could help me. 

I ran the code scripts/training/train_dex-net_2.0.sh. I got a final validation error of 12.239% with the precision-recall and roc curve attached. Is that what I expect to see? I'm confused because in the original paper you report an 85.7% accuracy on the validation set and a 92.2% accuracy here (https://berkeleyautomation.github.io/gqcnn/benchmarks/benchmarks.html). My result equals to neither of these so I would like to know what result should I expect?

Thank you in advance for your help and I look forward to hearing from you!

![roc](https://user-images.githubusercontent.com/29857603/72272117-18a64c00-35f6-11ea-9011-5a504f8a5f46.png)
![precision_recall](https://user-images.githubusercontent.com/29857603/72272123-19d77900-35f6-11ea-9437-7eed2137b878.png)

**Comment by JohnsonQi** [comment]
I have the same problem.

**Comment by visatish** [comment]
Resolved over email.
